name: Setup RAxML-NG
runs:
  using: composite
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
    - name: Setup RAxML-NG and RAxML-NG env variable
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        git clone --recursive https://github.com/amkozlov/raxml-ng.git
        cd raxml-ng && mkdir build && cd build
        cmake .. && make -j
        # set the raxmlng environment variable we need for the tests below
        cd .. && echo "raxmlng=$(pwd)/bin/raxml-ng" >> $GITHUB_ENV
      shell: bash