name: Build and test PyPythia
run-name: Build and run the tests of the PyPythia python library.
on: [push]
jobs:
  Run-Pythia-Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.13"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup RAxML-NG and RAxML-NG env variable
        uses: ./.github/actions/setup-raxmlng
      - name: Setup lightgbm requirements
        uses: ./.github/actions/setup-lightgbm
      - name: Install Pythia and setup requirements
        run: |
          pip install -e .
          pip install pytest
          rm tests/test_config.py
          echo "RAXMLNG_COMMAND = '${{ env.raxmlng }}'" > tests/test_config.py
          cat tests/test_config.py
      - name: Run Pythia tests
        run: |
          PYTHONPATH=. pytest

  Install-using-conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.13"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: etc/environment.yml
          cache-environment: true
          create-args:
            python=${{ matrix.python-version }}
      - name: Setup RAxML-NG and RAxML-NG env variable
        uses: ./.github/actions/setup-raxmlng
      - name: Test Pythia installation by running the CLI
        uses: ./.github/actions/test-pythia-cli

  Install-using-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Setup RAxML-NG and RAxML-NG env variable
        uses: ./.github/actions/setup-raxmlng
      - name: Setup lightgbm requirements
        uses: ./.github/actions/setup-lightgbm
      - name: Install Pythia using pip
        run: |
          pip install git+https://github.com/tschuelia/PyPythia.git
      - name: Test Pythia installation by running the CLI
        uses: ./.github/actions/test-pythia-cli

  Install-from-source:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Setup RAxML-NG and RAxML-NG env variable
        uses: ./.github/actions/setup-raxmlng
      - name: Setup lightgbm requirements
        uses: ./.github/actions/setup-lightgbm
      - name: Install from source
        run: |
          pip install .
      - name: Test Pythia installation by running the CLI
        uses: ./.github/actions/test-pythia-cli
